---
# tasks file for postgresql-slave
- name: Check for already in replication
  stat: path=/var/lib/postgresql/11/main/recovery.conf
  register: recovery

- name: Stop postgresql slave in order to sync
  service: 
    name: postgresql
    state: stopped
  when: not recovery.stat.exists

- name: Permit connections from outside
  blockinfile:
    dest: /etc/postgresql/11/main/pg_hba.conf
    block: |
      host      all       all     0.0.0.0/0   md5
  notify: reload postgresql

- name: EMPTY pgadata and copy ALL from master
  shell: |
    rm -rf /var/lib/postgresql/11/main/* && \
    /usr/bin/pg_basebackup \
      --write-recovery-conf \
      --pgdata=/var/lib/postgresql/11/main \
      --wal-method=stream \
      --dbname 'host={{master_addr}} port=5432 user=replicant password={{replicant_passwd}}' \
    2>&1
  become: yes
  become_user: postgres
  become_method: su
  when: not recovery.stat.exists
  notify: start postgresql
