---
# tasks file for postgresql-slave
- name: Stop postgresql slave in order to sync
  service: 
    name: postgresql
    state: stopped

- name: Permit connections from outside
  blockinfile:
    dest: /etc/postgresql/11/main/pg_hba.conf
    block: |
      host      login       all     0.0.0.0/0   md5

- name: EMPTY pgadata and copy ALL from master
  shell: |
    rm -rf /var/lib/postgresql/11/main/* && \
    /usr/bin/pg_basebackup \
      --write-recovery-conf \
      --pgdata=/var/lib/postgresql/11/main \
      --wal-method=stream \
      --dbname 'host={{master_addr}} port=5432 user=replicant password={{replicant_passwd}}' \
    2>&1
  become: yes
  become_user: postgres
  become_method: su

- name: Start postgresql pos sync
  service: 
    name: postgresql
    state: started
